### ISSUE TITLE
Support for file extensions different than .php

### ISSUE THREAD

**Issue by david0** [scrutinizer-ci/php-analyzer#138]
I noticed that the file extension of scanned files is hardcoded in [src/Scrutinizer/PhpAnalyzer/Model/File.php](https://github.com/scrutinizer-ci/php-analyzer/blob/master/src/Scrutinizer/PhpAnalyzer/Model/File.php?source=c#L51) and [src/Scrutinizer/PhpAnalyzer/Command/RunCommand.php](https://github.com/scrutinizer-ci/php-analyzer/blob/36a82213e272d5b6a158d223b9e35358e348c112/src/Scrutinizer/PhpAnalyzer/Command/RunCommand.php#L56).

Is this by design or is an PR for changing to configurable file extension(-s) welcome?

**Comment by DanielRuf** [comment]
+1

**Comment by FGM** [comment]
This is especially annoying when reviewing Drupal code, which expects .inc, .module, and .install to be used for specific variants of PHP code (specifically drush includes, modules, installer files).

The workaround is to create ugly things like foo_module.php and a foo.module just containing `require_once __DIR__ . '/foo_module.php';`, which needs extra stat() calls because of the require_once.

**Comment by markpavlitski** [comment]
+1 We're a Drupal shop too and this is a major pain point for us.

**Comment by schmittjoh** [comment]
We are actually testing this feature. It is not too far out.

**Comment by davidlukac** [comment]
:+1: Great! Looking forward.

**Comment by schmittjoh** [comment]
This is available in the latest version. We do support .module and .inc now.

**Comment by DanielRuf** [comment]
And .install and other extensions? Why not make this configurable for users?

**Comment by schmittjoh** [comment]
Is this commonly used somewhere?

**Comment by davidlukac** [comment]
Yes, `.install` files are commonly used e.g. in installation profiles. From Drupal.org:

### File Types

To have PhpStorm style Drupal files like .module, .profile, .admin.inc etc as .php files, Under PhpStorm's Preferences, IDE Settings, select File Types. To the right under Recognized Files Types, select PHP files (PHP) and then click the + sign in the Registered Patterns section. If you have followed the above instructions, **.module** will have already been added, but you will likely want to add **.admin.inc, .install, .profile (among others).** Hit Apply and OK to apply your new settings and your files will now all be styled nicely per PhpStorms styles for PHP.

_[source](https://www.drupal.org/node/1962108#file-types)_

**Comment by FGM** [comment]
Just loooking at today's Drupal 8.1 core, count of files by extension:

* 55 .install 
* 3 .engine
* 2 .profile
* 96 .inc
* 10 .theme

**Comment by Rytiss** [comment]
A lot of frameworks (e.g. CakePHP) use .tpl for templates that also contain PHP code.

I think you really need to support any extension.

**Comment by markpavlitski** [comment]
Drupal 7 also ships with php helper scripts with the .sh extension.
