### ISSUE TITLE
Method of trait not being picked up

### ISSUE THREAD

**Issue by sc0ttdav3y** [scrutinizer-ci/php-analyzer#327]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/datalink/crisisworks/inspections/a4c1aac9-6854-447f-bded-233d4bea5e20/issues/files/modules/asset/lib/Asset/Search/Filter/IsImpactedAsset.php?status=new&orderField=path&order=asc&issueId=fc80158b-19e1-4fbc-939e-6eb8afdcb484

**Comment by sascha-egerer** [comment]
Could you please close that issue @sc0ttdav3y
