### ISSUE TITLE
DateTimeInterface is part of PHP

### ISSUE THREAD

**Issue by cebe** [scrutinizer-ci/php-analyzer#330]
http://php.net/manual/de/class.datetimeinterface.php

an instanceof check does not hurt even in versions before 5.5

see https://scrutinizer-ci.com/g/yiisoft/yii2/issues/master/files/framework/base/Formatter.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=7ed72c4f-f283-48df-bd66-9f3d41cb0080

**Comment by eelkevdbos** [comment]
+1

**Comment by simensen** [comment]
:+1:

**Comment by s-miehlbradt** [comment]
Thanks for the bug report. A fix has been written and will be pushed to production soon.
