### ISSUE TITLE
Wrong stub for the MongoDate constructor

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#354]
The MongoDate constructor receives a timestamp as argument: http://fr2.php.net/manual/en/mongodate.construct.php

see https://scrutinizer-ci.com/g/Incenteev/Incenteev/inspections/9789d6ae-ef81-4276-a388-584ed4f8dab1/issues/files/src/Incenteev/WebBundle/Activity/MongoCollector.php?status=existing&orderField=path&order=asc&issueId=6fe065b8-e2a5-4c5e-a893-4da83fd5ae40

**Comment by pmaselkowski** [comment]
This has been fixed and can be closed.
