### ISSUE TITLE
The function strtr argument2 accept array 

### ISSUE THREAD

**Issue by overtrue** [scrutinizer-ci/php-analyzer#466]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/overtrue/pinyin/issues/master/files/src/Pinyin/Pinyin.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=15c6ea6d-a104-49b6-8fa4-4473567c9932

http://php.net/manual/zh/function.strtr.php

**Comment by schmittjoh** [comment]
This should be fixed.
