### ISSUE TITLE
Wrong analysis

### ISSUE THREAD

**Issue by ronisaha** [scrutinizer-ci/php-analyzer#469]
Wrong analysis

see https://scrutinizer-ci.com/g/xiidea/easy-audit/inspections/eb150f71-d6e2-46cc-8cf1-0f4bbbf4594f/issues/files/Resolver/EntityEventResolver.php?status=new&orderField=path&order=asc&issueId=5b1f755d-6d37-40e0-aebb-cb592b769ef7

**Comment by schmittjoh** [comment]
This should be fixed.
