### ISSUE TITLE
Invalid "too many arguments" issue for MongoTimestamp::__construct()

### ISSUE THREAD

**Issue by leedavis81** [scrutinizer-ci/php-analyzer#471]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/tthmedia/projectx/inspections/59ea8946-c44b-4ed7-befd-1e6c472e3e93/issues/files/application/models/Document/Repository/Lead.php?status=all&selectedLabels%5B0%5D=2&orderField=issueCount&order=desc&issueId=639da2a0-27ff-42f4-8b6d-78b8272c9e28

**Comment by schmittjoh** [comment]
This should be fixed.
