### ISSUE TITLE
Using FILE_USE_INCLUDE_PATH with file_get_contents should be valid

### ISSUE THREAD

**Issue by aidanlane** [scrutinizer-ci/php-analyzer#473]
See http://php.net/manual/en/function.file-get-contents.php

see https://scrutinizer-ci.com/g/aidanlane/alexandria/issues/master/files/src/wp-content/plugins/alex_interactive/public/class-alex-interactive.php?orderField=path&order=asc&issueId=707d2687-9b9c-415d-bf8f-54a6dc31ec8b

**Comment by schmittjoh** [comment]
This should be fixed.

**Comment by aidanlane** [comment]
Great, thanks!
