### ISSUE TITLE
stream_bucket_append

### ISSUE THREAD

**Issue by komex** [scrutinizer-ci/php-analyzer#478]
The second argument in ```stream_bucket_append()``` is not a resource type as described in [documentation](http://php.net/manual/en/function.stream-bucket-append.php). The argument must be an object which returns ```stream_bucket_make_writeable```.

see https://scrutinizer-ci.com/g/komex/influence/inspections/76ddd445-2220-4361-bb1f-0fd813afdbea/issues/files/src/Filter.php?status=existing&orderField=path&order=asc&issueId=ff35646f-c9b8-4ddd-883f-358850a0950e

**Comment by schmittjoh** [comment]
This should be fixed.
