### ISSUE TITLE
mysqli instead string

### ISSUE THREAD

**Issue by alexeygolovnya** [scrutinizer-ci/php-analyzer#479]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/juxta/juxta-php/issues/master/files/src/Db/Mysqli.php?selectedLabels%5B0%5D=7&orderField=path&order=asc&issueId=7bfe077c-7fe8-437e-a675-e2a62c5965f2

**Comment by schmittjoh** [comment]
This should be fixed.
