### ISSUE TITLE
Typecasting confused Scrutinizer in this case

### ISSUE THREAD

**Issue by ionux** [scrutinizer-ci/php-analyzer#480]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/ionux/php-bitpay-client/inspections/2af442d0-215b-4108-96bf-9f0d93a6c98f/issues/files/examples/CreateInvoice.php?status=new&orderField=path&order=asc&issueId=72dc120a-bc08-4662-98d4-481bb319b78a

**Comment by schmittjoh** [comment]
This should be fixed.
