### ISSUE TITLE
Incorrect mcrypt parameter bug found

### ISSUE THREAD

**Issue by ionux** [scrutinizer-ci/php-analyzer#481]
Scrutinizer is complaining about the second parameter for mcrypt_get_key_size() which is valid depending on which version of libmcrypt linked against. See: http://php.net/manual/en/function.mcrypt-get-key-size.php

see https://scrutinizer-ci.com/g/ionux/php-bitpay-client/inspections/2af442d0-215b-4108-96bf-9f0d93a6c98f/issues/files/src/Bitpay/Crypto/McryptExtension.php?status=new&orderField=path&order=asc&issueId=33054275-473c-48c9-92bd-97bbed61637c

**Comment by schmittjoh** [comment]
This should be fixed.
