### ISSUE TITLE
mysqli_result::fetch_assoc can't have any parameters.

### ISSUE THREAD

**Issue by wafflestealer654** [scrutinizer-ci/php-analyzer#484]
It says that it expects a parameter from calling `fetch_assoc` on `mysqli_result`. But according to the PHP documentation, it's only required if you're using the procedural version.

Documentation: http://php.net/manual/en/mysqli-result.fetch-assoc.php

see https://scrutinizer-ci.com/g/wafflesystems/dal/inspections/99dbdf28-77dd-444b-96fd-315bf447565a/issues/files/src/MySQLDatabase.php?status=existing&orderField=path&order=asc&issueId=24db8c49-2c75-4ef2-9cc0-85bcae418c1d

**Comment by schmittjoh** [comment]
This should be fixed.
