### ISSUE TITLE
Incorrect bug report for PHP ReflectionProperty::__construct

### ISSUE THREAD

**Issue by clubduece** [scrutinizer-ci/php-analyzer#486]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

As per the [PHP manual](http://php.net/manual/en/reflectionproperty.construct.php), ReflectionProperty::__Construct has two parameters.

see https://scrutinizer-ci.com/g/pods-framework/pods/inspections/256c2c6e-018e-4c09-bd1f-b4a990df5ef6/issues/files/tests/includes/testcase.php?status=existing&selectedLabels%5B0%5D=2&orderField=path&order=asc&issueId=c780dda7-04b4-4e67-ac5f-36772ac2d356

**Comment by schmittjoh** [comment]
This should be fixed.
