### ISSUE TITLE
Second parameter of exec() function is always an array

### ISSUE THREAD

**Issue by henriquemoody** [scrutinizer-ci/php-analyzer#489]
Even when [exec()](http://php.net/manual/en/function.exec.php) returns an empty string or get an error the second parameter is filled with an empty array.

**Example**: https://scrutinizer-ci.com/g/henriquemoody/Process/inspections/8992ac8a-c05f-47de-8b2e-879a24fd44f0/issues/files/src/Arara/Process/Action/Command.php?status=new&orderField=path&order=asc&issueId=f5009e03-1919-4fe7-b943-578d8c593633

**Comment by schmittjoh** [comment]
This should be fixed.
