### ISSUE TITLE
Bug: object reported as not traversable, when it is

### ISSUE THREAD

**Issue by stuartherbert** [scrutinizer-ci/php-analyzer#490]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/datasift/storyplayer/inspections/6ffd0eff-da3d-4cd9-853d-3edb94f55bac/issues/files/src/php/DataSift/Storyplayer/Injectables/ActiveSystemUnderTestConfigSupport.php?status=all&selectedSeverities%5B0%5D=10&orderField=path&order=asc&issueId=d7ee05d1-9bfd-481f-a01b-459cbb40b315

The class BaseObject extends stdClass. stdClass is traversable, and so is BaseObject as a result.

**Comment by schmittjoh** [comment]
This should be fixed.
