### ISSUE TITLE
Implode with one argument reports bug

### ISSUE THREAD

**Issue by michalfelski** [scrutinizer-ci/php-analyzer#491]
Hi

According to http://php.net/implode first parameter $glue is optional.

see https://scrutinizer-ci.com/b/gforces/netdirector-auto-v10/issues/develop/files/protected/components/Widget.php?selectedAuthors%5B0%5D=fela%40fela.pl&orderField=path&order=asc&issueId=3fa1c634-f938-455a-b621-259ba25d21d7

Thanks.

**Comment by schmittjoh** [comment]
This should be fixed.
