### ISSUE TITLE
The detection of coding against  a child class seems broken

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#495]
```
It seems like you code against a specific sub-type and not the parent class
 ``FOS\UserBundle\Model\User`` as the method ``setFirstName()`` does only exist in the 
following sub-classes of ``FOS\UserBundle\Model\User``: ``Incenteev\WebBundle\Entity\User``. 
```

But the line just before this is instantiating a ``Incenteev\WebBundle\Entity\User`` object, not a ``FOS\UserBundle\Model\User`` (which is an abstract class)

see https://scrutinizer-ci.com/g/Incenteev/Incenteev/inspections/f639162f-12c6-4df9-a663-f547a5a2a4a4/issues/files/src/Incenteev/WebBundle/DataFixtures/ORM/UserFixtures.php?status=new&orderField=path&order=asc&issueId=9f21680c-3aba-4b3c-84d8-1067fd830818

**Comment by schmittjoh** [comment]
The problem here is the return type of ``setEmail`` which is cached incorrectly. It was not reproducible with the current code-base, so closing this for now.
