### ISSUE TITLE
microtime(true)

### ISSUE THREAD

**Issue by kkashpur** [scrutinizer-ci/php-analyzer#498]
If the optional get_as_float is set to true then a float (in seconds) is returned.

see https://scrutinizer-ci.com/g/colonB/Dorm/issues/master/files/source/Dorm/Information/RunTime.php?selectedLabels%5B0%5D=7&orderField=path&order=asc&issueId=d70a92d3-5972-47a5-90e9-4ec610488a49

**Comment by schmittjoh** [comment]
This is fixed.
