### ISSUE TITLE
It is possible to have two params 

### ISSUE THREAD

**Issue by kkashpur** [scrutinizer-ci/php-analyzer#499]
http://php.net/manual/en/pdostatement.setfetchmode.php

see https://scrutinizer-ci.com/g/colonB/Dorm/issues/master/files/source/Dorm/Action/Select.php?selectedLabels%5B0%5D=2&orderField=path&order=asc&issueId=d3611d51-302f-4d18-b34e-c3418e6faf1e

**Comment by schmittjoh** [comment]
This should be fixed.
