### ISSUE TITLE
PhpAnalyzer does not handle use statements properly for inline phpdoc

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#501]
I have some inline phpdoc ``/** @var FileRepository $repository */``. PhpAnalyzer then reports than the method does not exist in ``Incenteev\WebBundle\Doctrine\Repository\FileRepository``, but the use statement is for ``Incenteev\WebBundle\Search\Repository\FileRepository``

see https://scrutinizer-ci.com/g/Incenteev/Incenteev/inspections/363e89c5-0a4a-4061-b7de-d7f4779c1f34/issues/files/src/Incenteev/WebBundle/Controller/SearchController.php?status=new&orderField=path&order=asc&issueId=06490c77-9ae0-4786-8df7-97bb8e14c9dc

**Comment by schmittjoh** [comment]
This is fixed.
