### ISSUE TITLE
False Positive mcrypt arguments

### ISSUE THREAD

**Issue by jaapio** [scrutinizer-ci/php-analyzer#502]
mcrypt functions do have 2 variants. The first one will except only one argument but the second one has two arugments. It depends on your libmcrypt version which one is applicable. 
From my point of view this is a false positive

see https://scrutinizer-ci.com/g/Ocramius/zf2/issues/master/files/library/Zend/Crypt/Symmetric/Mcrypt.php?selectedLabels%5B0%5D=2&orderField=path&order=asc&issueId=cf327eff-9308-470e-847a-02be4dda6a66

**Comment by schmittjoh** [comment]
This should be fixed.
