### ISSUE TITLE
Analyzer Confusing Return Value of Chained Function

### ISSUE THREAD

**Issue by mAAdhaTTah** [scrutinizer-ci/php-analyzer#505]
In the referenced code, I'm using a third-party package. I create a `client` object, and use that client to return a specific `api` object. There are many `api` objects depending on the endpoint you want to hit, and I can chain a method call on the `api` object directly:

```php
$this->client->api( 'me' )->show();
```

However, Scrutinizer can't seem to tell which `api` object I'm getting and "scrutinizes" my method call against all of them, giving me errors for missing arguments that are inaccurate.

see https://scrutinizer-ci.com/g/mAAdhaTTah/WP-Gistpen/inspections/8758c74a-3c7d-4fa3-b37d-0f2e75b4ccf9/issues/files/app/Account/Gist.php?status=new&selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=5f2aa846-fd66-470a-906d-1d6a400bd8e2

**Comment by schmittjoh** [comment]
Unfortunately, this is something we probably cannot fix as it requires knowledge about this API specifically. 

What you can do though is instead of ``->api('me')`` use ``->me()``, and the analyzer will infer the return value to the correct object.

Hope this helps.
