### ISSUE TITLE
An exception block is being reported as unreachable

### ISSUE THREAD

**Issue by adduc** [scrutinizer-ci/php-analyzer#506]
In the sample located at <https://scrutinizer-ci.com/g/filp/whoops/issues/master/files/src/Whoops/Provider/Silex/WhoopsServiceProvider.php?orderField=path&order=asc&issueId=317e4d8a-a5e1-4b88-a099-741e977c798f>, `$app` is an object implementing the ArrayAccess interface. When providing an index to retrieve that does not exist, an exception may be thrown.

**Comment by schmittjoh** [comment]
This is fixed.
