### ISSUE TITLE
Type checking ignores constructor's PHPDoc annotation

### ISSUE THREAD

**Issue by g105b** [scrutinizer-ci/php-analyzer#507]
The PathDetails class has a constructor that is documented to allow a `NodeList` object or an `array`, as seen here: https://github.com/BrightFlair/PHP.Gt/blob/master/src/ClientSide/PathDetails.php#L35

Where it is used in this file, an object of type `NodeList` is provided as the constructor's parameter: https://github.com/BrightFlair/PHP.Gt/blob/master/src/ClientSide/PageManifest.php#L66

... yet scrutinizer is reporting the function to only accept type `array`: https://scrutinizer-ci.com/g/BrightFlair/PHP.Gt/issues/master/files/src/ClientSide/PageManifest.php?orderField=path&order=asc&issueId=71c007eb-98e3-45ef-b1db-765278186eb3

**Comment by schmittjoh** [comment]
Your doc type refers to the parameter ``$domNodeList``, however it is actually named just ``$nodeList``. 

The analyzer will point out such errors now.
