### ISSUE TITLE
Analyzer incorrectly guesses the class of a returned object

### ISSUE THREAD

**Issue by miclf** [scrutinizer-ci/php-analyzer#508]
The analyzer thinks that the `redirect()` helper function returns an object of class `Illuminate\Http\RedirectResponse` when, in reality, the returned object has a class of `\Illuminate\Routing\Redirector`.

The type of the returned object depends on whether arguments have been provided to the function.

Please see the source of this function [here](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/helpers.php#L321).

see https://scrutinizer-ci.com/g/laravel/framework/inspections/c5c61540-2388-4666-b6e5-7a7f81fea03d/issues/files/src/Illuminate/Foundation/Auth/AuthenticatesAndRegistersUsers.php?status=new&selectedSeverities%5B0%5D=10&orderField=path&order=asc&issueId=5fb401a6-fed0-4e18-b4c2-364ed6f46f0b

**Comment by schmittjoh** [comment]
This is fixed.
