### ISSUE TITLE
Wrong unused code / variable detection

### ISSUE THREAD

**Issue by marc-mabe** [scrutinizer-ci/php-analyzer#510]
see https://scrutinizer-ci.com/g/Ocramius/zf2/issues/develop/files/library/Zend/Cache/Pattern/ClassCache.php?selectedAuthors%5B0%5D=marc-bennewitz%40arcor.de&orderField=path&order=asc&issueId=fb366596-8894-44f1-b857-6e73d960ba60

The variable `$name` given as first argument to the magic object method will be used as name of a static member with `$class::$name`.

**Comment by schmittjoh** [comment]
This could not be reproduced unfortunately, please re-open if this is still current.
