### ISSUE TITLE
__construct() returns itself not null.

### ISSUE THREAD

**Issue by CowChris** [scrutinizer-ci/php-analyzer#511]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

(This is a PHPStorm autocompleted suggestion). A __construct doesn't return null, really it returns the object itself. Scrutinizer suggests it should be returning Object|null.

Instead, would expect it to be OK with a __construct returning the Object.

see https://scrutinizer-ci.com/b/easyfundraising/domain/inspections/2f135151-19ad-4e9b-bdad-c8495f685774/issues/files/src/Payment/Detail/Cheque/Cheque.php?status=new&selectedAuthors%5B0%5D=chris%40easyfundraising.org.uk&orderField=path&order=asc&issueId=dd2d199d-5751-4d82-9d62-8e71e0f65c56

**Comment by schmittjoh** [comment]
This is fixed.
