### ISSUE TITLE
Return type suggested, "string[][]", but return type is already, "string[][]".

### ISSUE THREAD

**Issue by CowChris** [scrutinizer-ci/php-analyzer#512]
Scrutinizer suggested return PHPDoc was string[][], but it is already string[][].

see https://scrutinizer-ci.com/b/easyfundraising/domain/inspections/2f135151-19ad-4e9b-bdad-c8495f685774/issues/files/tests/Payment/Detail/Cheque/ChequeTest.php?status=new&selectedAuthors%5B0%5D=chris%40easyfundraising.org.uk&orderField=path&order=asc&issueId=6efe70b9-310d-4264-919f-47fb186434e5

**Comment by schmittjoh** [comment]
This is fixed.
