### ISSUE TITLE
Suggested @return annotation is identical to the one already in place...

### ISSUE THREAD

**Issue by CowChris** [scrutinizer-ci/php-analyzer#514]
Return annotation in the PHPDoc of a method is this:
```
     * @return CollectionInterface|ChangeInterface[] A change describing old and new payment methods.
     */
```

Scrutinizer suggests it should be changed to this:
```
Should the return type not be CollectionInterface|ChangeInterface[]?
```

The same!

![similar_change](https://cloud.githubusercontent.com/assets/405344/5487302/1db202d2-86a8-11e4-955a-459496fe52c0.png)

see https://scrutinizer-ci.com/b/easyfundraising/domain/inspections/f92d12a1-a683-4108-8be7-8ae20f045082/issues/files/src/Cause/Payment/Detail/Change/Repository.php?status=new&selectedSeverities%5B0%5D=1&orderField=path&order=asc&issueId=3182617d-9fc1-4bd7-9307-7637e51a0f09

**Comment by schmittjoh** [comment]
Fixed, too.
