### ISSUE TITLE
Unknown diffrence to parent return type

### ISSUE THREAD

**Issue by dominikzogg** [scrutinizer-ci/php-analyzer#519]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/saxulum/saxulum-model-generator/inspections/478e5f87-7d47-489c-b1c3-7b9ae8d1715f/issues/files/src/DoctrineOrm/Type/Simple/IdType.php?status=all&selectedSeverities%5B0%5D=10&orderField=path&order=asc&issueId=35ef2ecd-63d8-454e-abea-9430dc634c24

**Comment by schmittjoh** [comment]
This is fixed.
