### ISSUE TITLE
Documentation error if PHP ArrayAccess interface is implemented

### ISSUE THREAD

**Issue by aimeos** [scrutinizer-ci/php-analyzer#523]
If an object implements the PHP ArrayAccess interface so properties can be set via $object['property'], a documentation issue is reported because PHPAnalyzer thinks the object is an array. Examples are the Symfony\Component\DomCrawler\Form objects:

$form = $crawler->filter( '.catalog-filter .btn-action' )->form();
$form['f-attr-id'] = array( $id => $id );
$crawler = $client->submit( $form );

-> $form of type array&lt;string,array&lt;...y&lt;?,?&gt;"}>, but the function expects a object<Symfony\Component\DomCrawler\Form>.

see https://scrutinizer-ci.com/g/aimeos/aimeos-symfony2/inspections/0d134b8a-a2e3-463f-a1b7-b9388897251d/issues/files/Tests/Controller/PageControllerTest.php?status=all&orderField=path&order=asc&issueId=d3787eb5-5bad-4ff2-9703-f176270a960f

**Comment by schmittjoh** [comment]
This is likely happening because the $crawler variable is unknown, and hence the $form variable, too. In such a case, the analyzer currently assumes that it is an array when using it as an array.

I'd suggest to just ignore this specific issue.
