### ISSUE TITLE
When adding phpdoc for a method, the patch has a wrong indentation

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#525]
see the 4th patch in https://scrutinizer-ci.com/g/Behat/Behat/inspections/8322aa43-d58e-4659-8ba4-25180f60d61a/patches

**Comment by schmittjoh** [comment]
This was a regression, and fixed.

**Comment by stof** [comment]
not fixed actually: https://scrutinizer-ci.com/g/minkphp/Mink/inspections/ee3a5d08-67b8-4f2f-8995-2c9d263dc352/patches

**Comment by schmittjoh** [comment]
It's not yet live.

**Comment by nazar-pc** [comment]
@schmittjoh, looks like I encounter the same issue, when will it be deployed?
https://scrutinizer-ci.com/g/nazar-pc/CleverStyle-CMS/inspections/38876629-58ea-4d2b-b987-d4f89027e15b/patches?status=all&selectedCategories[0]=Indentation
