### ISSUE TITLE
Incorrect Use statement detection 

### ISSUE THREAD

**Issue by mwjames** [scrutinizer-ci/php-analyzer#527]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticInterlanguageLinks/inspections/b7e51ff0-3251-4752-8bc8-a4d3df30e223/issues/files/src/Search/MappedSearchResultSet.php?status=new&orderField=path&order=asc&issueId=97eaed16-2133-4b18-9c08-04514542483a

I have seen it several times (and not only in this repo) where `php-analyzer` reports a missing use statement when in fact the `use ...` is placed at the top of the php file.

**Comment by oparoz** [comment]
Same problem here:
see https://scrutinizer-ci.com/g/interfasys/galleryplus/inspections/d8adcd63-acb6-4b8b-bbd4-4c09d3704f40/issues/files/service/service.php?status=new&orderField=path&order=asc&issueId=5724839d-11b2-4e82-85ed-4be39106a791

**Comment by schmittjoh** [comment]
We will be adding a better error message for this case. The causes for this typically are either:

- the class is defined in a folder that is not analyzed by us (like excluded in your ``filter`` section), or
- the class is only available in a newer version of your dependencies than the one listed in your composer.json/composer.lock file

**Comment by mwjames** [comment]
> the class is defined in a folder that is not analyzed by us (like excluded in your filter section), or

You want to take care of the severity in cases where you can't analyze the `use` statement because marking it as `major` doesn't add much value for those classes.

**Comment by schmittjoh** [comment]
Yes, we are going to add a new issue basically for when the use statement is there, but the class was still not found.
