### ISSUE TITLE
Incorrect ‘This method is not used’

### ISSUE THREAD

**Issue by ddeboer** [scrutinizer-ci/php-analyzer#530]
Private method `getServerString()` is reported as unused, but it is used (from `authenticate()`):

see https://scrutinizer-ci.com/g/ddeboer/imap/inspections/c87ad404-757e-4dc5-8182-c2ff13d877d9/issues/files/src/Server.php?status=new&orderField=path&order=asc&issueId=c1a3f007-2587-4df3-a39b-6a8c2b2f86b6

**Comment by schmittjoh** [comment]
This is fixed.

**Comment by ddeboer** [comment]
Thanks!
