### ISSUE TITLE
Assignment to $final_landing_page is dead?

### ISSUE THREAD

**Issue by ghalusa** [scrutinizer-ci/php-analyzer#531]
$final_landing_page is used on line 59 in the redirect.

see https://scrutinizer-ci.com/g/ghalusa/PHP-Skeleton-App/issues/master/files/authenticate/controllers/show_login_form.php?orderField=path&order=asc&issueId=098076dd-5251-4c73-8a28-6da160756905

**Comment by schmittjoh** [comment]
It seems like there is another definition of this variable on line 57 which always overwrites the flagged one on line 55.
