### ISSUE TITLE
Analyzer seems not to check 'finally' statement for variable usage.

### ISSUE THREAD

**Issue by neomerx** [scrutinizer-ci/php-analyzer#532]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

The variable is used in the following 'finally' block.

see https://scrutinizer-ci.com/g/neomerx/core/issues/dev/files/src/Models/Category.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc&issueId=48493137-cd1e-4d02-8741-03e0f7410b55

**Comment by schmittjoh** [comment]
Thanks, this is fixed.
