### ISSUE TITLE
http://php.net/manual/en/memcached.quit.php

### ISSUE THREAD

**Issue by assertchris** [scrutinizer-ci/php-analyzer#533]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/revolvephp/assistant/inspections/1abd476e-634c-4577-8d82-8b4c9cb61d6a/issues/files/src/Provider/Memcached/Messenger.php?status=new&orderField=path&order=asc&issueId=eaa78ffe-0d1c-4134-a198-47d8292afdb0

**Comment by schmittjoh** [comment]
Thanks, this is fixed.
