### ISSUE TITLE
Analyzer doesn't consider 'empty()' as valid type check for null

### ISSUE THREAD

**Issue by neomerx** [scrutinizer-ci/php-analyzer#536]
The following code generates false positive warning that null could be passed to function
empty($nullable) === true ?: someFunction($nullable);

see https://scrutinizer-ci.com/g/neomerx/core/inspections/60d2ff8f-3bad-40f6-bf3b-d4cb173ddd18/issues/files/src/Repositories/BaseRepository.php?status=new&orderField=path&order=asc&issueId=1aef34e6-6cb0-4b54-a444-7e16c3af53ba

**Comment by neomerx** [comment]
Analyzer gives false positive on ordinary 'if' with 2 parameters
if (empty($parameters) === false and empty($rules) === false) {
  ...
 says both $parameters and $rules could be null here
}

**Comment by neomerx** [comment]
@schmittjoh is it fixable?

**Comment by schmittjoh** [comment]
Yes, sure. What should already work fine is if you do not use a comparison like this for example ``if ( ! empty($parameters) && ! empty($rules))``. We should obviously support your variant, too.

**Comment by neomerx** [comment]
@schmittjoh Thanks a lot for promt reply. I don't have many of these in my code so I just hide a few similar issues.

**Comment by schmittjoh** [comment]
This is fixed.
