### ISSUE TITLE
Wrong multiple @return statement

### ISSUE THREAD

**Issue by kkashpur** [scrutinizer-ci/php-analyzer#537]
Scrutinizer parser doesn`t track returning multiple statement in a parent doc

in parent:
/**
 * @return string|integer
 */ 
in child:
/**
 * @return string|integer
 */ 
it guesses that child has integer and parent - string type
see https://scrutinizer-ci.com/g/colonB/Dorm/issues/master/files/source/Dorm/Cache/Driver/Simple.php?selectedLabels%5B0%5D=18&orderField=path&order=asc&issueId=2c90c2cc-c1dd-45f8-85fa-e4725bcdd485

**Comment by schmittjoh** [comment]
Could you elaborate this a bit more, not sure I understand the problem, yet?
