### ISSUE TITLE
Wrong phpdoc analyze ?

### ISSUE THREAD

**Issue by tyx** [scrutinizer-ci/php-analyzer#545]
On this code
```
            $currentRegexes = Yaml::parse(file_get_contents($file->getPathname()));
            $cleanedCurrentRegexes = $this->cleanNullEntry($currentRegexes);
```

> It seems like $currentRegexes defined by \Symfony\Component\Yaml\...ile->getPathname())) on line 45 can also be of type string; however, Api\Common\UI\Console\Us...mmand::cleanNullEntry() does only seem to accept array, maybe add an additional type check? 

But according yo `Symfony\Component\Yaml\Yaml::parse` phpdoc, it seems it can return only array.

**Comment by schmittjoh** [comment]
PHP Analyzer ignores doc comments if it believes that they are out-dated/wrong.

In this case, the ``Yaml::parse`` function is annotated to return an ``array``. However, it calls the ``Parser::parse`` function that is annotated with ``mixed`` and in fact does not only return arrays.

If you are sure that you only get back an array, feel free to ignore this comment though.
