### ISSUE TITLE
Empty hooking methods

### ISSUE THREAD

**Issue by dominikzogg** [scrutinizer-ci/php-analyzer#548]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/saxulum/saxulum-crud/inspections/0590cff2-c727-4e4f-84fe-3faabfce6868/issues/files/src/Controller/CrudTrait.php?status=all&orderField=path&order=asc&issueId=e006aad5-b13f-41c9-b778-38cc95175940

It seems its not possible to define empty hooking methods which aren't abstract, without getting this issue.

Any idea?

**Comment by schmittjoh** [comment]
Starting with the next version, we will automatically assume empty methods to have side-effects. So, this issue will not show up anymore.
