### ISSUE TITLE
$final_landing_page is not dead

### ISSUE THREAD

**Issue by ghalusa** [scrutinizer-ci/php-analyzer#550]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/ghalusa/PHP-Skeleton-App/inspections/bcd2aec7-95f2-42e6-aca6-bfa5653a6f1d/issues/files/authenticate/controllers/show_login_form.php?status=existing&orderField=path&order=asc&issueId=098076dd-5251-4c73-8a28-6da160756905

**Comment by schmittjoh** [comment]
It seems like you assign this variable two lines below this issue as such the previous assignment is never used (and dead).

If I missed something, please re-open.

**Comment by ghalusa** [comment]
I see now. Thanks. I guess I'll just convert all of that to a switch statement, for clarity.
