### ISSUE TITLE
func_get_args()

### ISSUE THREAD

**Issue by bubach** [scrutinizer-ci/php-analyzer#554]
When using func_get_args() I get an error about not using the arguments, it doesn't seem to understand that this function collects them all into an array.

**Comment by schmittjoh** [comment]
We do check for this function, do you have link to the issue so we can have a look?

**Comment by bubach** [comment]
Well, now I can't find it. So.. ehrm. Never mind.

**Comment by schmittjoh** [comment]
No problem, please re-open if this comes up again.
