### ISSUE TITLE
The class PHPUnit_Framework_Error does not exist ?

### ISSUE THREAD

**Issue by fruitl00p** [scrutinizer-ci/php-analyzer#556]
In one of my unittests i expect and catch a PHPunit exception.. Thus i try to catch it as explicitly as possible. This gives a false positive of the undefined class.. (which is provided by phpunit ;))

Any way to fix this issue ? What should i change to keep the unittest / check and still resolve the scrutinizer 'bug' ?

see https://scrutinizer-ci.com/g/fruitl00p/php-mt940/issues/master/files/test/Kingsquare/parser/banking/mt940/engine/getInstanceTest.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=a07e1ec9-79d8-48b6-8e46-7b175618468b

**Comment by fruitl00p** [comment]
see also #382

**Comment by GrahamCampbell** [comment]
This is not a bug. You haven't added phpunit to your require-dev section in your composer.json. That's 100% required.

**Comment by fruitl00p** [comment]
Thanks @GrahamCampbell indeed i was missing the require-dev. (more or less defacto for me anyway :D )
