### ISSUE TITLE
Wrong analysis is done for dev versions of dependencies

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#576]
I updated my project dependencies, making it use the latest 2.6.x-dev version of symfony/symfony while it was using 2.6.1 previously. PhpAnalyzer now tells me that ``isGranted`` does not exist in my controllers, which is totally wrong. It looks like it uses the wrong version of the code.

see https://scrutinizer-ci.com/g/Incenteev/Incenteev/inspections/87cd2053-a228-48bc-9bd3-edd7d1c18b30/issues/files/src/Incenteev/WebBundle/Controller/NotificationController.php?status=new&orderField=path&order=asc&issueId=d8691160-7edc-4982-b802-e2f288ebee8d

**Comment by schmittjoh** [comment]
There was a problem if a dependency of a dependency was using a different version than your root package. We now prioritize dependencies of the root package which fixes this.

**Comment by stof** [comment]
@schmittjoh Couldn't you use the dependencies being locked ? I have a lock file in the repo for this project
