### ISSUE TITLE
To support sami/sami (https://github.com/FriendsOfPHP/Sami) this syntax must be used for documentation on variadic functions.

### ISSUE THREAD

**Issue by robfrawley** [scrutinizer-ci/php-analyzer#585]
see https://scrutinizer-ci.com/g/scribenet/symfony-cache-bundle/inspections/01086298-e000-4bb7-a752-7d9200b7ace7/issues/files/src/KeyGenerator/KeyGeneratorInterface.php?status=existing&orderField=path&order=asc&issueId=e988d157-44ac-4de9-831a-c6e53a8eceea

Should be able to use:
```php
/**
 * Set the values used to generate the key
 *
 * @param  ...mixed $values
 * @return $this
 */
public function setKeyValues(...$values);
```

to support sami/sami API docs.

**Comment by schmittjoh** [comment]
This has been fixed in the latest dev version.

**Comment by robfrawley** [comment]
Wonderful; thanks!
