### ISSUE TITLE
Some dependencies could not be analyzed

### ISSUE THREAD

**Issue by senkal** [scrutinizer-ci/php-analyzer#594]
Hi,
For some time PHP analyser doesn't work because of error in few dependencies(we have composer.lock in repo).
https://scrutinizer-ci.com/g/feelunique/frontend/inspections/c8a62056-be94-4870-b1ab-343de124b8ac#

Some dependencies could not be analysed:
- **guzzle/guzzle** I know where is the issue so it's fine.
- **doctrine/mongodb-odm** - issue is `Error while resolving doc type "$cursor": Unknown type name "$cursor" at position 0.`. I look at the code and couldn't find the issue at all :(
- **doctrine/dbal** the error is not in the log, have no idea how to track the issue

Is there a way to disable dependency check for some libs?
Or to get much more detailed logs?
Maybe I should disable PHP analyzer all together because it marks inspections as red now.

**Comment by schmittjoh** [comment]
This should be fixed now. Let me know if you still see this.

**Comment by senkal** [comment]
Looks fine.
3rd party issues don't block analysis part any more.
It was fast :D
