### ISSUE TITLE
$filterType usage return $filterType ? $is : !$is;

### ISSUE THREAD

**Issue by RobinCK** [scrutinizer-ci/php-analyzer#596]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/RobinCK/reflection/issues/master/files/ReflectionClass.php?selectedLabels%5B0%5D=2&orderField=path&order=asc&issueId=338a2725-4cc3-45b7-82eb-cd520d53fc5a

**Comment by schmittjoh** [comment]
This usage is inside a closure though; the variable is not defined by the outer function. It seems like you have some sort of error there.

**Comment by RobinCK** [comment]
Thanks you! And sorry did not notice the error.
