### ISSUE TITLE
MIssing class error. 

### ISSUE THREAD

**Issue by leedavis81** [scrutinizer-ci/php-analyzer#611]
The class has been explicitly declared (via use) at the top of the file (use System\Field\StorageField;). No idea why I'm getting a class doesn't exist error.

see https://scrutinizer-ci.com/g/tthmedia/projectx/issues/master/files/application/models/Document/Lead.php?selectedLabels%5B0%5D=3&selectedLabels%5B1%5D=9&orderField=path&order=asc&issueId=3f0837fd-f2ac-4530-b2f3-9eb780ed583f

**Comment by schmittjoh** [comment]
Thanks for reporting. Is this class maybe defined by a dependency that is not listed in your composer file, or in a path that has been excluded?

**Comment by leedavis81** [comment]
Hi, 

It's within my composer autoload settings:

    "autoload": {
        "classmap": ["application/"],
        "psr-0": {
            "System\\": "library/",

Also, no excludes set up anywhere. Class is in place along with many others that don't trigger any errors.

**Comment by schmittjoh** [comment]
I've checked your config, and the library path was currently excluded. I've moved this to a dependency now, and this should be fine on next inspection. You can view the updated config here:
https://scrutinizer-ci.com/g/tthmedia/projectx/settings/build-config

**Comment by leedavis81** [comment]
Ah ha! Didn't realise I'd put that in there. Thanks.
