### ISSUE TITLE
Condition count wrong

### ISSUE THREAD

**Issue by TomBZombie** [scrutinizer-ci/php-analyzer#623]
https://scrutinizer-ci.com/g/TomBZombie/Maphper/code-structure/master/operation/Maphper%5CMaphper%3A%3AoffsetSet

Given the following code:

```php

	public function offsetSet($offset, $value) {
		foreach ($this->relations as $name => $relation) {
			//If a relation has been overridden, run the overwrite	
			if (isset($value->$name) &&	!($value->$name instanceof Relation\One)) $relation->overwrite($value, $value->$name);			
		}
		
		$value = $this->wrap($this->processFilters($value), true);
		
		$pk = $this->dataSource->getPrimaryKey();
		if ($offset !== null) $value->{$pk[0]} = $offset;
		$this->dataSource->save($value);		
	}
```

It's showing as 5 conditions... by my count it's 4: 

- foreach ($this->relations as $name => $relation)
- isset($value->$name)
- !($value->$name instanceof Relation\One)
- if ($offset !== null)

**Comment by schmittjoh** [comment]
That's correct, each method/function has a conditional complexity of 1 per definition; that's why it's 5 in total.
