### ISSUE TITLE
"add instanceof check" to something that has an instanceof check

### ISSUE THREAD

**Issue by yoosefi** [scrutinizer-ci/php-analyzer#634]
see https://scrutinizer-ci.com/g/hfw/h/issues/master/files/src/D.php?orderField=path&order=asc&issueId=b2530791-7263-4dbc-818a-62469ac0d171

**Comment by schmittjoh** [comment]
If you still check for the interface only, how do you know that it has this property (as interface have no properties in PHP)?

**Comment by yoosefi** [comment]
must've slipped my mind, thanks. nevermind.
