### ISSUE TITLE
Issue in PHPDoc with multiple types.

### ISSUE THREAD

**Issue by mmoreram** [scrutinizer-ci/php-analyzer#657]
Sometimes, when a variable is defined in PHPDoc as two variables at the same time...
``` php
/**
 * @var Bundle|Plugin $plugin
 */
$plugin->getPath();
```
a message is thrown telling that method `getPath` is only available in `$pugin`. Well, with this annotation, I am specifying that both classes represent this variable (for example, two interfaces), so a method could be defined only in one class.

see https://scrutinizer-ci.com/g/elcodi/elcodi/issues/master/files/src/Elcodi/Component/Plugin/Services/PluginManager.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=26bb7a94-f4b1-4136-a0ed-9dbf309ec246

**Comment by schmittjoh** [comment]
Unfortunately, there is no annotation to do what you said. The meaning of this annotation is either this type (``Bundle``) or that type (``Plugin``), but it does not mean both at the same time.

If you want both at the same time, you would need an interface that extends both types which probably makes sense if you check for that in your code often.

**Comment by mmoreram** [comment]
http://www.phpdoc.org/docs/latest/guides/types.html#multiple-types-combined

As you can see... "Some IDE's do exactly what they want..."

Sorry for bothering! And thanks :)
