### ISSUE TITLE
Variable type not recognized

### ISSUE THREAD

**Issue by mmoreram** [scrutinizer-ci/php-analyzer#658]
PHP Analyzer is not understanding that the variable type is being redefined when is needed.

``` php
$var = string|false;
if ($var === false) $var = string;
return $var;
```

see https://scrutinizer-ci.com/g/elcodi/elcodi/issues/master/files/src/Elcodi/Component/EntityTranslator/Services/CachedEntityTranslationProvider.php?selectedLabels%5B0%5D=9&orderField=path&order=asc&issueId=a01d8782-22ea-4774-adfe-39ce95c23ca9

**Comment by schmittjoh** [comment]
Are you sure that it is ``string|false`` and not ``string|boolean`` what the cache method returns?

**Comment by mmoreram** [comment]
Absolutely right. Good catch! :D Thanks.
