### ISSUE TITLE
DateTime implements DateTimeInterface on PHP 5.5+, but the analyzer does not know it

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/php-analyzer#675]
see https://scrutinizer-ci.com/g/Incenteev/Incenteev/inspections/95dfeb2c-1205-4fff-bffc-465ffa9234dc/issues/files/src/Incenteev/WebBundle/Space/Graph/ResultsGraphBuilder.php?status=new&orderField=path&order=asc&issueId=b762a398-b838-4b3c-b6a2-202d5be07d60

**Comment by stof** [comment]
@schmittjoh any ETA for the proper support of DateTimeInterface ?

**Comment by s-miehlbradt** [comment]
Thanks for the bug report. A fix has been written and will be pushed to production soon.
