### ISSUE TITLE
Analyzer fails to comprehend DateTime as implementation of DateTimeInterface 

### ISSUE THREAD

**Issue by rocketricardo** [scrutinizer-ci/php-analyzer#683]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/g/rocket-internet-berlin/TMLSCX/inspections/634015be-08af-4966-a0a2-836c742c7664/issues/files/scx/src/RocketLabs/SellerCenterExpress/IdentityBundle/Command/SellerWorkerCommand.php?status=new&orderField=path&order=asc&issueId=b69b4ff7-3be1-4d52-bc50-39259443d429

**Comment by s-miehlbradt** [comment]
Thanks for the bug report. A fix has been written and will be pushed to production soon.
