### ISSUE TITLE
Not consistent behaviour when returning a mix of types

### ISSUE THREAD

**Issue by m038** [scrutinizer-ci/php-analyzer#729]
I'm getting a _bug_ report from the analyzer that my code might return a mix of types and i should add an additional type check. For my specific case, this is not true. 
Please see the [interface](https://github.com/m038/contentapi-sdk-php/blob/master/src/Superdesk/ContentApiSdk/Client/FileGetContentsClient.php#L56) for an idea of the implementation of my method. This method will only return an array when the fourth parameter _$returnFullResponse_ is set to true. This is enforced in the specs for each class that implements this interface, e.g. [this client](https://github.com/m038/contentapi-sdk-php/blob/master/src/Superdesk/ContentApiSdk/Client/FileGetContentsClient.php#L56).
As you can see [where](https://github.com/m038/contentapi-sdk-php/blob/master/src/Superdesk/ContentApiSdk/ContentApiSdk.php#L69) i'm calling the method _makeApiCall_ i'm omitting the fourth parameter, so it defaults to false. Therefore it won't return an Array.

The desciption is based on the following issue: https://scrutinizer-ci.com/g/superdesk/contentapi-sdk-php/issues/master/files/src/Superdesk/ContentApiSdk/ContentApiSdk.php?orderField=path&order=asc&issueId=97998666-bbb2-4c40-a362-c6dfdb917998

**Comment by nasimnabavi** [comment]
Thank you for the report.
Currently the return type is inferred from the Interface's return type and not the sub-implementations.
You can filter such an issues:
https://scrutinizer-ci.com/docs/reviews/filtering_issues_and_false_positives

Bests
