### ISSUE TITLE
The variable does not seem to be defined

### ISSUE THREAD

**Issue by gulaandrij** [scrutinizer-ci/php-analyzer#731]
If variable is not defined or it is "false" we return null string

see https://scrutinizer-ci.com/g/imagecms/ImageCMS/issues/development/files/application/helpers/admin_helper.php?orderField=path&order=asc&issueId=51ae4fcb-148e-4609-a776-1ade27b7d204

**Comment by nasimnabavi** [comment]
Thank you for the report.
it is generally a good practice to add "array()" regardless of the code behaviour.
