### ISSUE TITLE
`$foo = bar($foo);` reports a bug saying `$foo` is the return type of `bar()`

### ISSUE THREAD

**Issue by KorvinSzanto** [scrutinizer-ci/php-analyzer#733]
No type check is needed since I can be certain that `$docblocks` is an array.

see https://scrutinizer-ci.com/g/concrete5/documentation_generator/inspections/2f32f1cf-9400-4255-9acc-441adce873f1/code-structure/class/Concrete%5CDocumentationGenerator%5CConfig%5CCommentRepository?issueId=7f8f513a-44d5-45f1-ad05-0aae14671bfa

**Comment by nasimnabavi** [comment]
Thanks for the report.
Unfortunately we cannot fix the issue, since the data for the above link has already been purged from our systems.
