### ISSUE TITLE
preg_match() with PREG_OFFSET_CAPTURE is integer

### ISSUE THREAD

**Issue by thunderer** [scrutinizer-ci/php-analyzer#735]
[This comparison](https://scrutinizer-ci.com/g/thunderer/Shortcode/code-structure/master/operation/Thunder%5CShortcode%5CParser%5CRegexParser%3A%3AparseSingle?issueId=0861a746-2210-4fd3-81f1-ce08332a8cee) is reported as unnecessary, but it's correct and required. When using flag PREG_OFFSET_CAPTURE, offsets reported at `[1]` position in each match are integers, not strings. Value `-1` is reported when given capture group was not found. Thanks in advance for correcting that behavior.

**Comment by nasimnabavi** [comment]
Thank you for the report.
We have fixed the issue. It will be available soon.

Bests
