### ISSUE TITLE
задача 1

### ISSUE THREAD

**Issue by dimaxz** [scrutinizer-ci/php-analyzer#787]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

see https://scrutinizer-ci.com/b/dimax_lanetz/ddd-test/issues/master/files/index.php?selectedLabels%5B0%5D=18&orderField=path&order=asc&issueId=4ba425f8-72ce-4864-869e-a0f7103105f7

**Comment by s-miehlbradt** [comment]
The issue could not be reproduced. 

If it is still current, please open a new issue.

Thank you
