### ISSUE TITLE
Confusion between interface and implementation

### ISSUE THREAD

**Issue by onema** [scrutinizer-ci/php-analyzer#794]
In this case the event dispatcher implements the interface EventDispatcherInterface, hence this is invalid.

see https://scrutinizer-ci.com/g/onema/classyfile/inspections/66e03e34-3bf6-499e-b283-375349cbb2b8/issues/files/src/ClassyFile.php?status=existing&orderField=path&order=asc&issueId=0ffb8fce-4b2e-469d-9fcb-becc5ffd33dd

**Comment by nasimnabavi** [comment]
Actually Line.72 ($this->dispatcher = $dispatcher;) is producing the issue.
$dispatcher which is from the type of EventDispatcherInterface, might not be an instance of EventDispatcher, but another sub-class which is also implementing EventDispatcherInterface.
So an 'instanceof' check is needed to make the assignment valid.
