### ISSUE TITLE
variable marked as unused when it is being used

### ISSUE THREAD

**Issue by cvweiss** [scrutinizer-ci/php-analyzer#796]
> Here, you can explain why the found issue was invalid, and what result
> you would have expected otherwise.
>
> Please also check that this issue has not already been reported.

$httpCode is used as a return value after the do/while loop

see https://scrutinizer-ci.com/g/zKillboard/zKillboard/issues/master/files/classes/CrestTools.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc&issueId=c15e28f2-7d61-4f56-84c7-0edcdc837f8b

**Comment by nasimnabavi** [comment]
$httpCode is immediately overwritten in do-while. So the $httpCode=null is not used and can be removed.

**Comment by cvweiss** [comment]
It's also good practice to define the variable before the loop when it is being used after the loop.
