### ISSUE TITLE
Error on Preparing Dependencies with PHP Analyzer

### ISSUE THREAD

**Issue by arcanedev-maroc** [scrutinizer-ci/php-analyzer#800]
It's been 2 days i'm struggling with this error, it's says:

```
Persisting data... An error occurred during analysis (Event-ID some-random-id)

Please try again or email support@scrutinizer-ci.com if this error persists.
```

This occur when the project cache is disabled.

For more details: https://scrutinizer-ci.com/g/ARCANESOFT/Settings/inspections/ac91a567-4617-41f5-a5e2-29cf481ba484

**Comment by jaykravetz** [comment]
We've been experiencing the same issue since we upgraded to Laravel 5.2. I reached out to support and still have not heard back. Any information on this would be really appreciated.

**Comment by arcanedev-maroc** [comment]
Have this issue with Laravel 5.1

**Comment by arcanedev-maroc** [comment]
Hi @schmittjoh, can you give us any explanations about this issue ??

**Comment by arcanedev-maroc** [comment]
Please @schmittjoh, can you help us with this issue ??

This issue drives me crazy and i don't wanna switch to another CI (many of my projects rely on Scrutinizer CI).

Please check what's wrong with the `php-analyzer` while analyzing the `laravel/framework`.

Thanks.

**Comment by arcanedev-maroc** [comment]
The issue is solved ! :relieved:
