### ISSUE TITLE
Incorrect issue raised in PHP7 with declare(strict_types=1);

### ISSUE THREAD

**Issue by garethellis36** [scrutinizer-ci/php-analyzer#801]
The following issue is incorrectly raised when using strict typing in PHP7:

> For compatibility and reusability of your code, PSR1 recommends that a file should either new symbols (like classes, functions, etc.) or have side-effects (like outputting something, or including other files), but not both at the same time. The first symbol is defined on line 4 and the first side effect is on line 2.

Sample code:

```php
<?php
declare(strict_types=1);

interface Foo
{
    public function bar(): SomeClass;
}
```

**Comment by s-miehlbradt** [comment]
Thank you for taking the time to inform us about this problem.

We have made a note of the issue.
