### ISSUE TITLE
Setting Class Implementing Interface is marked as incompatible with declared type

### ISSUE THREAD

**Issue by heiglandreas** [scrutinizer-ci/php-analyzer#802]
As you can see [here](https://scrutinizer-ci.com/g/joindin/callingallpapers-cli/inspections/5936c5cb-fdf3-451f-af22-58cea3147a34/issues/files/src/Parser/JoindinCfpParser.php?status=new&orderField=path&order=asc&honorSelectedPaths=0) Scrutinizer remarks that the given Object (an instance of ```\DateTimeImmutable```) is not compatible with the declared type (which is ```\DateTimeInterface```). As far as I know ```DateTimeImmutable``` implements ```\DateTimeInterface``` and therefore that message is just wrong. See also the [PHP-Documentation to ```DateTimeImmutable```]( http://php.net/DateTimeImmutable)

![bildschirmfoto 2016-03-04 um 08 03 11](https://cloud.githubusercontent.com/assets/91998/13520658/8f92a898-e1e2-11e5-839b-9fde8b6f60bd.png)

**Comment by s-miehlbradt** [comment]
We have made a note of the issue and are working on a fix.

**Comment by s-miehlbradt** [comment]
The issue has been fixed.

Thank you for taking the time.
