### ISSUE TITLE
PHP 7.1: Invalid strings in arithmetic

### ISSUE THREAD

**Issue by pento** [scrutinizer-ci/php-analyzer#805]
PHP 7.1 will add this new restriction to arithmetic operations:

https://wiki.php.net/rfc/invalid_strings_in_arithmetic

It'd be handy if possible problem code was detected.

**Comment by schmittjoh** [comment]
Thanks for suggesting. I've moved this to an internal issue, closing here.

**Comment by pento** [comment]
Good news! Will this ticket be updated, or is there somewhere else I should subscribe for information about when this is available?
